export const CATEGORY_LABELS: Record<string, string> = {
  "abap": "ABAP",
  "accessibility": "无障碍",
  "advanced": "高级",
  "agents": "Agent",
  "agile": "敏捷",
  "ai": "AI",
  "ai-ml": "AI/机器学习",
  "analysis": "分析",
  "api": "API",
  "architecture": "架构",
  "assets": "资源",
  "automation": "自动化",
  "automation devops": "自动化/DevOps",
  "blockchain": "区块链",
  "btp": "BTP",
  "business": "商业",
  "business sales": "商业/销售",
  "cap": "CAP",
  "code quality testing": "代码质量/测试",
  "code-review": "代码评审",
  "commands": "命令",
  "communication": "沟通",
  "community": "社区",
  "content": "内容",
  "customization": "定制",
  "data": "数据",
  "data analytics": "数据分析",
  "data-analytics": "数据分析",
  "database": "数据库",
  "debugging": "调试",
  "design": "设计",
  "design ux": "设计/UX",
  "developer-tools": "开发者工具",
  "development": "开发",
  "development engineering": "研发工程",
  "development-tools": "开发工具",
  "development-utilities": "开发辅助",
  "devops": "DevOps",
  "document-conversion": "文档转换",
  "documentation": "文档",
  "education": "教育",
  "essentials": "必备",
  "explore": "探索",
  "finance": "金融",
  "game-development": "游戏开发",
  "gaming": "游戏",
  "general": "通用",
  "git workflow": "Git 工作流",
  "hana": "HANA",
  "hooks": "Hooks",
  "infrastructure": "基础设施",
  "integration": "集成",
  "languages": "语言",
  "learning": "学习",
  "marketing": "营销",
  "marketing growth": "营销增长",
  "media": "媒体",
  "modernization": "现代化改造",
  "official claude code plugins": "Claude Code 官方插件",
  "operations": "运营",
  "payments": "支付",
  "performance": "性能",
  "personality": "个性化",
  "plan": "规划",
  "productivity": "效率",
  "project & product management": "项目/产品管理",
  "qol": "体验优化",
  "quality": "质量",
  "refactoring": "重构",
  "security": "安全",
  "security, compliance, & legal": "安全/合规/法务",
  "super": "增强",
  "testing": "测试",
  "tooling": "工具链",
  "tools": "工具",
  "ui": "UI",
  "ui-development": "UI 开发",
  "utilities": "实用工具",
  "version-control": "版本控制",
  "web development": "Web 开发",
  "workflow": "工作流",
  "workflow orchestration": "工作流编排",
  "workflows": "工作流",
  "%": "%",
};

export const getCategoryLabel = (category: string): string => {
  return CATEGORY_LABELS[category] ?? category;
};
